version: "3.8"
services:
  # gem-transaction-processor:
  #   container_name: gem-transaction-processor
  #   image: gem-transaction-processor
  #   build:
  #     context: ./packages/gem-transaction-processor
  #   ports:
  #     - "3001:3000"
  #   command: bash -c "yarn migrate:run  && node src/main.js"
  #   environment:
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=admin
  #     - POSTGRES_DB=gem_transaction_processor_db
  #     - POSTGRES_HOST=gem_transaction_processor_db

  #   depends_on:
  #     - gem_transaction_processor_db

  gem_transaction_processor_db:
    container_name: gem_transaction_processor_db
    image: "postgres:12"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gem_transaction_processor_db
      - POSTGRES_PORT=5432
    volumes:
      - gem_transaction_processor_db_data:/var/lib/postgresql/data

volumes:
  gem_transaction_processor_db_data: {}
